language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
  - pip install flake8
script:
  - coverage run ./tests/tests.py
  - codecov
  - flake8 --ignore=E501  # ignore "line too long errors"